### ISSUE TITLE
Questions about Mask3D performance

### ISSUE THREAD

**Issue by Dingry** [zju3dv/SAM-Graph#2]
Hi, thank you for your inspiring work. I've noticed in Table 2 that Mask3D's performance is much lower than its reported 70+ AP50 on ScanNet val and test set. I am curious about your implementation and evaluation. Could you please clarify this more? Thanks so much for you time.

<img width="344" alt="image" src="https://github.com/zju3dv/SAM-Graph/assets/39176662/feca2362-3675-435a-ac9a-95fbd189597c">

**Comment by ghy0324** [comment]
Hi! Thanks for your interest!
Since our method is class-agnostic, we ignored the categories when calculating the AP (Average Precision) for all methods during evaluation, which results in numerical differences from normal AP. Please refer to the paper for detailed evaluation strategy, and we will make the code (including evaluation) public.
